+++
SergeySharashkin/js-comand-prog pull request #60
Opened 2021-12-10 23:50 UTC by Althaen

Добавил уведомления и спиннер

2021-12-11 08:39 UTC, NataliaBulanova commented on src/js/Trailer/getTrailerUrl.js
> +import Notiflix from 'notiflix';
Почему не так,
import { Loading },
 если в этом файле используется только спинер?

2021-12-11 08:40 UTC, NataliaBulanova commented on src/js/Trailer/getTrailerUrl.js
> +    Notiflix.Loading.pulse({ svgColor: '#ff6b08' });
И тут тогда будет просто 
Loading.pulse({ svgColor: '#ff6b08' });

2021-12-11 08:42 UTC, NataliaBulanova commented on src/js/main.js
> +import Notiflix from 'notiflix';
А тут только {Notify} можно импортировать

2021-12-11 08:43 UTC, NataliaBulanova commented on src/js/main.js
> +    Notiflix.Notify.warning('Query string can not be empty');
Ну и тут поменять на 
Notify.warning('Query string can not be empty');

2021-12-11 08:44 UTC, NataliaBulanova commented on src/js/openInfoModal.js
> +import Notiflix from 'notiflix';
тут тоже только {Notify} импортить можно

2021-12-11 13:42 UTC, Althaen commented on src/js/Trailer/getTrailerUrl.js
> +import Notiflix from 'notiflix';
Да, ты права, просто я в спешке делал. По-хорошему нужно было отдельно подключать блоки Loading и Notification. Думал это потом на рефакторинг оставить

2021-12-11 20:01 UTC, SergeySharashkin requested changes
пофикси сейчас это перед пушем и залей себе в ветку дев, уже сейчасесть 3 конфликта

2021-12-12 10:05 UTC, NataliaBulanova approved these changes

2021-12-12 10:30 UTC, NataliaBulanova approved these changes

2021-12-12 11:19 UTC, SergeySharashkin approved these changes

2021-12-12 11:19 UTC, merged